services:
  - type: web
    name: image-compressor
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y libvips libvips-dev
      pip install -r requirements.txt
    startCommand: gunicorn app:app
