services:
  - type: web
    name: image-compressor
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y libvips libvips-dev
      vips -l | head -n 1
      pip install -r requirements.txt
    startCommand: gunicorn app:app
